runtime: python27
api_version: 1
threadsafe: true


  
handlers:
- url: /lib/requests
  script: Scrape.app

handlers:
- url: /requests
  script: Scrape.app

handlers:
- url: /mysql/connector
  script: Scrape.app

handlers:
- url: /bs4/
  script: Scrape.app
  
handlers:
- url: /.*
  script: Scrape.app

handlers:
- url: /.*/.*
  script: Scrape.app
  
handlers:
- url: /.*/.*/.*
  script: Scrape.app
  
handlers:
- url: /.*/.*/.*/.*
  script: Scrape.app
